/**
 * Unit tests for DriftComparator (T-05).
 *
 * All three ComparisonResult outcomes are covered via a table-driven test.
 * Additional cases verify whitespace-normalisation behaviour and handling of
 * functions with an empty jsdoc.
 */

import { describe, it, expect } from 'vitest';
import { compareDrift } from '../../src/drift-comparator.js';
import type { ExportedFunction, DocSection } from '../../src/types.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Builds a minimal ExportedFunction with optional overrides. */
function makeFn(overrides: Partial<ExportedFunction> = {}): ExportedFunction {
  return {
    name: 'myFunction',
    signature: 'export function myFunction(x: string): number',
    jsdoc: 'Converts a string to a number.\n\n@param x - The input string.\n@returns The numeric value.',
    sourceFilePath: 'src/utils.ts',
    changeType: 'modified',
    ...overrides,
  };
}

/** Builds a minimal DocSection with optional overrides. */
function makeSection(overrides: Partial<DocSection> = {}): DocSection {
  return {
    functionName: 'myFunction',
    target: 'markdown',
    sectionContent: '',
    ...overrides,
  };
}

/**
 * Produces the canonical section string matching the format generated by the
 * comparator internally, so tests can construct "current" content without
 * duplicating internal logic in an error-prone way.
 */
function canonical(fn: ExportedFunction): string {
  return [
    `## ${fn.name}`,
    '',
    '```typescript',
    fn.signature,
    '```',
    '',
    fn.jsdoc,
  ].join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Table-driven tests — all three ComparisonResult outcomes
// ---------------------------------------------------------------------------

describe('compareDrift — table-driven', () => {
  const fn = makeFn();

  const cases: Array<{
    label: string;
    section: DocSection;
    expected: 'not-found' | 'current' | 'stale';
  }> = [
    {
      label: 'not-found: target is not-found',
      section: makeSection({ target: 'not-found', sectionContent: '' }),
      expected: 'not-found',
    },
    {
      label: 'current: section content matches canonical rendering exactly',
      section: makeSection({ sectionContent: canonical(fn) }),
      expected: 'current',
    },
    {
      label: 'stale: signature differs',
      section: makeSection({
        sectionContent: canonical(
          makeFn({ signature: 'export function myFunction(x: number): string' }),
        ),
      }),
      expected: 'stale',
    },
    {
      label: 'stale: jsdoc body differs',
      section: makeSection({
        sectionContent: canonical(makeFn({ jsdoc: 'Old description.' })),
      }),
      expected: 'stale',
    },
    {
      label: 'stale: function name in heading differs',
      section: makeSection({
        sectionContent: canonical(makeFn({ name: 'otherFunction' })),
      }),
      expected: 'stale',
    },
  ];

  for (const { label, section, expected } of cases) {
    it(label, () => {
      expect(compareDrift(fn, section)).toBe(expected);
    });
  }
});

// ---------------------------------------------------------------------------
// Whitespace normalisation
// ---------------------------------------------------------------------------

describe('compareDrift — whitespace normalisation', () => {
  it('treats extra trailing newlines in sectionContent as current', () => {
    const fn = makeFn();
    const section = makeSection({
      sectionContent: canonical(fn) + '\n\n', // extra trailing blank lines
    });
    expect(compareDrift(fn, section)).toBe('current');
  });

  it('collapses multiple blank lines in sectionContent when comparing', () => {
    const fn = makeFn();
    // Insert extra blank lines between heading and code fence
    const withExtraBlankLines = canonical(fn).replace(
      `## ${fn.name}\n\n\`\`\`typescript`,
      `## ${fn.name}\n\n\n\n\`\`\`typescript`,
    );
    const section = makeSection({ sectionContent: withExtraBlankLines });
    expect(compareDrift(fn, section)).toBe('current');
  });

  it('treats leading whitespace in sectionContent as current', () => {
    const fn = makeFn();
    const section = makeSection({
      sectionContent: '\n\n' + canonical(fn),
    });
    expect(compareDrift(fn, section)).toBe('current');
  });
});

// ---------------------------------------------------------------------------
// Edge cases
// ---------------------------------------------------------------------------

describe('compareDrift — edge cases', () => {
  it('handles empty jsdoc: returns current when section matches no-jsdoc form', () => {
    const fn = makeFn({ jsdoc: '' });
    const section = makeSection({ sectionContent: canonical(fn) });
    expect(compareDrift(fn, section)).toBe('current');
  });

  it('handles confluence target: returns current when content matches', () => {
    const fn = makeFn();
    const section = makeSection({
      target: 'confluence',
      confluencePageId: '32833537',
      sectionContent: canonical(fn),
    });
    expect(compareDrift(fn, section)).toBe('current');
  });

  it('handles confluence target: returns stale when content differs', () => {
    const fn = makeFn();
    const section = makeSection({
      target: 'confluence',
      confluencePageId: '32833537',
      sectionContent: canonical(makeFn({ jsdoc: 'Outdated docs.' })),
    });
    expect(compareDrift(fn, section)).toBe('stale');
  });

  it('not-found ignores sectionContent value', () => {
    const fn = makeFn();
    // Even if sectionContent accidentally contains matching text, target wins
    const section = makeSection({
      target: 'not-found',
      sectionContent: canonical(fn),
    });
    expect(compareDrift(fn, section)).toBe('not-found');
  });
});
